"use client";
import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { Coins, Crown, Gamepad2, Home, Lock, Pause, Play, RotateCcw, Shield, ShoppingBag, Sparkles, Trophy, Volume2, VolumeX, Zap } from "lucide-react";
import { LEVELS, SHOP_ITEMS, UPGRADES, type GDLevel, type ShopItem, type UpgradeId } from "@/lib/geometryData";

type View = "home" | "levels" | "shop" | "upgrades" | "play";
type Tab = "skin" | "background" | "trail";
type Save = { coins:number; unlockedLevel:number; completed:number[]; best:Record<number,number>; secretCoins:string[]; owned:string[]; skin:string; background:string; trail:string; upgrades:Record<UpgradeId,number> };
type Run = { x:number; y:number; vy:number; rotation:number; onGround:boolean; deaths:number; coins:number; collected:string[]; shieldUsed:boolean; done:boolean; won:boolean; percent:number };
type Particle = {x:number;y:number;vx:number;vy:number;life:number;size:number;hue:number};

const KEY="geometry-dash-uno-v2";
const DEFAULT:Save={coins:0,unlockedLevel:1,completed:[],best:{},secretCoins:[],owned:["skin-classic","bg-day","trail-none"],skin:"skin-classic",background:"bg-day",trail:"trail-none",upgrades:{jump:0,magnet:0,shield:0,multiplier:0}};
const THEMES:any={neon:["#10153b","#23407d","#55e7ff"],sunset:["#30133a","#ae4145","#ffd166"],forest:["#0d2b28","#21715d","#7dffb2"],void:["#090817","#261553","#cf9cff"],ice:["#102d45","#61afd9","#dffaff"],lava:["#25080d","#86251c","#ffcf55"]};
const item=(id:string)=>SHOP_ITEMS.find(x=>x.id===id)||SHOP_ITEMS[0];
const diff=(x:string)=>x==="Démoniaque"?"DEMON":x==="Expert"?"INSANE":x==="Difficile"?"HARD":"NORMAL";
const cls=(x:string)=>x.toLowerCase().replace(/é/g,"e");

function cube(ctx:CanvasRenderingContext2D,x:number,y:number,size:number,skin:ShopItem,r:number){ctx.save();ctx.translate(x+size/2,y+size/2);ctx.rotate(r);const c=skin.color||"#fff",a=skin.accent||"#55e7ff";ctx.shadowBlur=18;ctx.shadowColor=a;ctx.fillStyle=c;ctx.fillRect(-size/2,-size/2,size,size);ctx.shadowBlur=0;ctx.lineWidth=3;ctx.strokeStyle=a;ctx.strokeRect(-size/2,-size/2,size,size);ctx.fillStyle=a;ctx.fillRect(-size*.18,-size*.1,size*.1,size*.1);ctx.fillRect(size*.08,-size*.1,size*.1,size*.1);ctx.strokeStyle=a;ctx.beginPath();ctx.moveTo(-size*.18,size*.17);ctx.lineTo(0,size*.24);ctx.lineTo(size*.18,size*.17);ctx.stroke();ctx.restore()}
function bg(ctx:CanvasRenderingContext2D,w:number,h:number,id:string,theme:string,camera:number){const b=item(id),t=THEMES[theme]||THEMES.neon;let c1=b.color||t[0],c2=b.accent||t[1];if(id==="bg-day"){c1="#63cbff";c2="#b8efff"}if(id==="bg-space"){c1="#070716";c2="#34205e"}if(id==="bg-lava"){c1="#21070a";c2="#76231b"}const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,c1);g.addColorStop(1,c2);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<20;i++){const x=((i*317-camera*.16)%(w+140))-70,y=60+(i*83%380);ctx.globalAlpha=.2;ctx.fillStyle=i%2?"#fff":t[2];ctx.beginPath();ctx.arc(x,y,12+i%4*7,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function sound(kind:string){try{const AC=window.AudioContext||((window as any).webkitAudioContext as typeof AudioContext);if(!AC)return;const a=new AC(),o=a.createOscillator(),g=a.createGain();const f=kind==="jump"?360:kind==="coin"?760:kind==="win"?560:130;o.type=kind==="death"?"sawtooth":"square";o.frequency.value=f;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();o.frequency.exponentialRampToValueAtTime(f*(kind==="death"?.45:1.6),a.currentTime+.09);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.14);o.stop(a.currentTime+.15);setTimeout(()=>a.close(),220)}catch{}}

export default function GeometryDashGame(){
 const [view,setView]=useState<View>("home"),[save,setSave]=useState<Save>(DEFAULT),[ready,setReady]=useState(false),[levelId,setLevelId]=useState(1),[run,setRun]=useState<Run|null>(null),[paused,setPaused]=useState(false),[muted,setMuted]=useState(false),[tab,setTab]=useState<Tab>("skin"),[toast,setToast]=useState(""),[help,setHelp]=useState(false);
 const say=useCallback((s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)},[]);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setSave({...DEFAULT,...JSON.parse(raw)})}catch{}setReady(true)},[]); useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(save))},[ready,save]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if(view==="play"&&(e.code==="Space"||e.code==="ArrowUp"||e.code==="KeyW")){e.preventDefault();dispatchEvent(new CustomEvent("gd-jump"))}if(view==="play"&&e.code==="Escape")setPaused(x=>!x)};addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[view]);
 const start=(id:number)=>{if(id>save.unlockedLevel)return;setLevelId(id);setRun({x:180,y:430,vy:0,rotation:0,onGround:true,deaths:0,coins:0,collected:[],shieldUsed:false,done:false,won:false,percent:0});setPaused(false);setView("play")};
 const buy=(it:ShopItem)=>{if((it.unlockLevel||1)>save.unlockedLevel){say(`Niveau ${it.unlockLevel} requis.`);return}if(save.owned.includes(it.id)){setSave(s=>({...s,...(it.category==="skin"?{skin:it.id}:it.category==="background"?{background:it.id}:{trail:it.id})}));say("Équipé ✨");return}if(save.coins<it.price){say("Pas assez de pièces.");return}setSave(s=>({...s,coins:s.coins-it.price,owned:[...s.owned,it.id],...(it.category==="skin"?{skin:it.id}:it.category==="background"?{background:it.id}:{trail:it.id})}));say(`${it.name} acheté 🔥`)};
 const upgrade=(id:UpgradeId)=>{const u=UPGRADES.find(x=>x.id===id),lv=save.upgrades[id]||0;if(!u||lv>=u.max)return;if(save.coins<u.costs[lv]){say("Pas assez de pièces.");return}setSave(s=>({...s,coins:s.coins-u.costs[lv],upgrades:{...s.upgrades,[id]:lv+1}}));say(`${u.name} niveau ${lv+1} ⚡`)};
 const finish=(l:GDLevel,r:Run)=>{const reward=Math.round(80+l.id*25+r.coins*(1+save.upgrades.multiplier*.1)+120);setSave(s=>({...s,coins:s.coins+reward,unlockedLevel:Math.max(s.unlockedLevel,Math.min(LEVELS.length,l.id+1)),completed:s.completed.includes(l.id)?s.completed:[...s.completed,l.id],best:{...s.best,[l.id]:100},secretCoins:[...new Set([...s.secretCoins,...r.collected])]}));if(!muted)sound("win");setRun({...r,done:true,won:true,percent:100})};
 if(!ready)return <div className="gd-loading"><div className="gd-loader-cube"/><b>CHARGEMENT DU MONDE…</b></div>;
 const current=LEVELS.find(l=>l.id===levelId)||LEVELS[0],featured=LEVELS[Math.min(save.unlockedLevel-1,3)]||LEVELS[0];
in(save.unlockedLevel-1,3)]||LEVELS[0];
 return <div className={view==="play"?"gd-app gd-playing":"gd-app"}>
  {view!=="play"&&<Nav view={view} go={setView} save={save} muted={muted} setMuted={setMuted}/>} 
  {view==="home"&&<Home save={save} featured={featured} start={start} go={setView} help={setHelp}/>}
  {view==="levels"&&<Levels save={save} selected={levelId} select={setLevelId} start={start} go={setView}/>} 
  {view==="shop"&&<Shop save={save} tab={tab} setTab={setTab} buy={buy} go={setView}/>} 
  {view==="upgrades"&&<Upgrades save={save} upgrade={upgrade} go={setView}/>} 
  {view==="play"&&run&&<Game level={current} save={save} run={run} paused={paused} muted={muted} setRun={setRun} setPaused={setPaused} finish={finish} retry={()=>start(current.id)} exit={()=>{setRun(null);setView("levels")}}/>}
  {toast&&<div className="gd-toast">{toast}</div>}
  {help&&<div className="gd-modal-backdrop" onClick={()=>setHelp(false)}><div className="gd-help-modal" onClick={e=>e.stopPropagation()}><button className="gd-modal-x" onClick={()=>setHelp(false)}>×</button><span className="gd-kicker">COMMANDES</span><h2>Maîtrise ton cube.</h2><div className="gd-help-grid"><div><b>ESPACE / ↑ / W</b><span>Sauter</span></div><div><b>CLIC / TAP</b><span>Sauter</span></div><div><b>ÉCHAP</b><span>Pause</span></div><div><b>ORBES</b><span>Saute près de l'orbe pour l'activer</span></div></div><button className="gd-primary-btn" onClick={()=>{setHelp(false);start(featured.id)}}><Play size={17} fill="currentColor"/> C'est parti</button></div></div>}
  {view!=="play"&&<footer className="gd-footer"><span>UNO → <b>GEOMETRY DASH WORLD</b></span><span>Progression locale sauvegardée automatiquement</span></footer>}
 </div>
}

function Nav({view,go,save,muted,setMuted}:{view:View;go:(v:View)=>void;save:Save;muted:boolean;setMuted:(v:boolean)=>void}){return <header className="gd-topbar"><button className="gd-logo" onClick={()=>go("home")}><span className="gd-logo-cube">✦</span><span><b>GEOMETRY</b><small>DASH // UNO WORLD</small></span></button><nav>{[["home","Accueil"],["levels","Niveaux"],["shop","Boutique"],["upgrades","Améliorations"]].map(([v,l])=><button key={v} className={view===v?"active":""} onClick={()=>go(v as View)}>{l}</button>)}</nav><div className="gd-nav-right"><span className="gd-coin-pill">◆ {save.coins}</span><button className="gd-icon-btn" onClick={()=>setMuted(!muted)}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}</button></div></header>}

function Home({save,featured,start,go,help}:{save:Save;featured:GDLevel;start:(n:number)=>void;go:(v:View)=>void;help:(b:boolean)=>void}){return <main className="gd-home"><section className="gd-hero"><div className="gd-hero-copy"><span className="gd-kicker"><Sparkles size={14}/> THE UNO WORLD HAS CHANGED</span><h1>RUN.<br/><span>JUMP.</span><br/>BREAK THE LIMIT.</h1><p>Un runner de précision façon Geometry Dash : 8 niveaux, 24 pièces secrètes, cubes, fonds, trails et améliorations permanentes.</p><div className="gd-hero-actions"><button className="gd-primary-btn big" onClick={()=>start(featured.id)}><Play size={19} fill="currentColor"/> JOUER</button><button className="gd-secondary-btn big" onClick={()=>go("levels")}><Gamepad2 size={19}/> NIVEAUX</button></div><button className="gd-help-link" onClick={()=>help(true)}>Comment jouer ? →</button></div><HeroArt level={featured}/></section><div className="gd-stats-row"><Stat icon={<Trophy size={18}/>} v={`${save.completed.length}/${LEVELS.length}`} l="Niveaux terminés"/><Stat icon={<Coins size={18}/>} v={`${save.secretCoins.length}/24`} l="Pièces secrètes"/><Stat icon={<Zap size={18}/>} v={`LVL ${save.unlockedLevel}`} l="Progression"/><Stat icon={<Sparkles size={18}/>} v={`${save.owned.length}`} l="Objets"/></div><section className="gd-home-panels"><div className="gd-panel"><div className="gd-panel-head"><div><span className="gd-kicker">EN VEDETTE</span><h2>{featured.name}</h2></div><i className={`gd-diff ${cls(featured.difficulty)}`}>{diff(featured.difficulty)}</i></div><p>⚡ {Math.round(featured.speed)} vitesse · ◆ 3 pièces · record {save.best[featured.id]||0}%</p><button className="gd-secondary-btn" onClick={()=>start(featured.id)}>Continuer →</button></div><div className="gd-panel"><span className="gd-kicker">TON STYLE</span><h2>Personnalise ton run.</h2><div className="gd-mini-cards"><Mini it={item(save.skin)}/><Mini it={item(save.background)}/><Mini it={item(save.trail)}/></div><button className="gd-secondary-btn" onClick={()=>go("shop")}><ShoppingBag size={16}/> Boutique</button></div></section><section className="gd-callout"><div><span className="gd-kicker">NO CHECKPOINTS. NO EXCUSES.</span><h2>Chaque tentative te rapproche du 100%.</h2><p>Les bonnes runs commencent toujours par un premier essai.</p></div><button className="gd-primary-btn" onClick={()=>go("upgrades")}>DEVENIR PLUS FORT</button></section></main>}
function Stat({icon,v,l}:{icon:ReactNode;v:string;l:string}){return <div className="gd-stat"><span>{icon}</span><div><b>{v}</b><small>{l}</small></div></div>}
function Mini({it}:{it:ShopItem}){return <div className="gd-mini-item"><div className="gd-mini-preview" style={{background:it.color||"#172042",boxShadow:`inset 0 0 30px ${(it.accent||"#72edff")}55`}}>{it.category==="skin"?"◆":it.category==="trail"?"✦":"☁"}</div><b>{it.name}</b></div>}
function HeroArt({level}:{level:GDLevel}){return <div className="gd-hero-art"><div className="gd-sun"/><div className="gd-grid-floor"/><div className="gd-art-platform p1"/><div className="gd-art-platform p2"/><div className="gd-art-spike s1"/><div className="gd-art-spike s2"/><div className="gd-art-spike s3"/><div className="gd-art-coin">◆</div><div className="gd-art-orb">●</div><div className="gd-art-cube"><span>• •</span><i>⌣</i></div><div className="gd-art-label"><b>LEVEL {level.id}</b><span>{level.name}</span><em>{diff(level.difficulty)}</em></div></div>}

function Levels({save,selected,select,start,go}:{save:Save;selected:number;select:(n:number)=>void;start:(n:number)=>void;go:(v:View)=>void}){const l=LEVELS.find(x=>x.id===selected)||LEVELS[0];return <main className="gd-screen"><div className="gd-screen-head"><div><span className="gd-kicker">WORLD MAP</span><h1>Choisis ton niveau.</h1><p>8 niveaux, 3 pièces secrètes chacun, difficulté qui monte jusqu'au DEMON.</p></div><button className="gd-secondary-btn" onClick={()=>go("home")}><Home size={17}/> Accueil</button></div><div className="gd-level-layout"><div className="gd-level-list">{LEVELS.map(x=>{const lock=x.id>save.unlockedLevel;return <button key={x.id} disabled={lock} onClick={()=>select(x.id)} className={`gd-level-card ${selected===x.id?"selected":""} ${lock?"locked":""}`}><div className="gd-level-number">{lock?<Lock size={20}/>:String(x.id).padStart(2,"0")}</div><div className="gd-level-main"><b>{x.name}</b><span><i className={`gd-diff ${cls(x.difficulty)}`}>{diff(x.difficulty)}</i><em>{save.best[x.id]||0}%</em></span><div className="gd-level-bar"><span style={{width:`${save.best[x.id]||0}%`}}/></div></div><div className="gd-level-stars">{save.completed.includes(x.id)?"★":"☆"}</div></button>})}</div><div className="gd-level-detail"><span className="gd-kicker">LEVEL {l.id}</span><h2>{l.name}</h2><div className="gd-detail-tags"><i className={`gd-diff ${cls(l.difficulty)}`}>{diff(l.difficulty)}</i><span>⚡ {Math.round(l.speed)}</span><span>◆ 3</span></div><div className="gd-detail-visual"><div className="gd-detail-cube">• •<small>⌣</small></div><div className="gd-detail-spike"/><div className="gd-detail-spike two"/><div className="gd-detail-coin">◆</div></div><div className="gd-detail-row"><span>Record</span><b>{save.best[l.id]||0}%</b></div><div className="gd-detail-row"><span>Pièces</span><b>{l.coins.filter(c=>save.secretCoins.includes(c.id)).length}/3</b></div><button className="gd-primary-btn full" onClick={()=>start(l.id)}><Play size={18} fill="currentColor"/> LANCER</button></div></div></main>}

span>Sauter</span></div><div><b>CLIC / TAP</b><span>Sauter</span></div><div><b>ÉCHAP</b><span>Pause</span></div><div><b>ORBES</b><span>Saute près de l'orbe pour l'activer</span></div></div><button className="gd-primary-btn" onClick={()=>{setHelp(false);start(featured.id)}}><Play size={17} fill="currentColor"/> C'est parti</button></div></div>}
  {view!=="play"&&<footer className="gd-footer"><span>UNO → <b>GEOMETRY DASH WORLD</b></span><span>Progression locale sauvegardée automatiquement</span></footer>}
 </div>
}

function Nav({view,go,save,muted,setMuted}:{view:View;go:(v:View)=>void;save:Save;muted:boolean;setMuted:(v:boolean)=>void}){return <header className="gd-topbar"><button className="gd-logo" onClick={()=>go("home")}><span className="gd-logo-cube">✦</span><span><b>GEOMETRY</b><small>DASH // UNO WORLD</small></span></button><nav>{[["home","Accueil"],["levels","Niveaux"],["shop","Boutique"],["upgrades","Améliorations"]].map(([v,l])=><button key={v} className={view===v?"active":""} onClick={()=>go(v as View)}>{l}</button>)}</nav><div className="gd-nav-right"><span className="gd-coin-pill">◆ {save.coins}</span><button className="gd-icon-btn" onClick={()=>setMuted(!muted)}>{muted?