"use client";
import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { Coins, Crown, Gamepad2, Home as HomeIcon, Lock, Pause, Play, RotateCcw, Shield, ShoppingBag, Sparkles, Trophy, Volume2, VolumeX, Zap } from "lucide-react";
import { LEVELS, SHOP_ITEMS, UPGRADES, type GDLevel, type ShopItem, type UpgradeId } from "@/lib/geometryData";

type View = "home" | "levels" | "shop" | "upgrades" | "play";
type Tab = "skin" | "background" | "trail";
type Save = { coins:number; unlockedLevel:number; completed:number[]; best:Record<number,number>; secretCoins:string[]; owned:string[]; skin:string; background:string; trail:string; upgrades:Record<UpgradeId,number>; dailyClaimDate:string; dailyStreak:number; claimedMissions:string[] };
type Run = { x:number; y:number; vy:number; rotation:number; onGround:boolean; deaths:number; coins:number; collected:string[]; shieldUsed:boolean; done:boolean; won:boolean; percent:number; practice:boolean; checkpointX:number; checkpointY:number; checkpointCoins:number; checkpointCollected:string[] };
type Particle = {x:number;y:number;vx:number;vy:number;life:number;size:number;hue:number};

const KEY="geometry-dash-uno-v2";
const DEFAULT:Save={coins:0,unlockedLevel:1,completed:[],best:{},secretCoins:[],owned:["skin-classic","bg-day","trail-none"],skin:"skin-classic",background:"bg-day",trail:"trail-none",upgrades:{jump:0,magnet:0,shield:0,multiplier:0},dailyClaimDate:"",dailyStreak:0,claimedMissions:[]};
const THEMES:any={neon:["#10153b","#23407d","#55e7ff"],sunset:["#30133a","#ae4145","#ffd166"],forest:["#0d2b28","#21715d","#7dffb2"],void:["#090817","#261553","#cf9cff"],ice:["#102d45","#61afd9","#dffaff"],lava:["#25080d","#86251c","#ffcf55"]};
const item=(id:string)=>SHOP_ITEMS.find(x=>x.id===id)||SHOP_ITEMS[0];
const diff=(x:string)=>x==="Démoniaque"?"DEMON":x==="Expert"?"INSANE":x==="Difficile"?"HARD":"NORMAL";
const cls=(x:string)=>x.toLowerCase().replace(/é/g,"e");

function cube(ctx:CanvasRenderingContext2D,x:number,y:number,size:number,skin:ShopItem,r:number){ctx.save();ctx.translate(x+size/2,y+size/2);ctx.rotate(r);const c=skin.color||"#fff",a=skin.accent||"#55e7ff";ctx.shadowBlur=18;ctx.shadowColor=a;ctx.fillStyle=c;ctx.fillRect(-size/2,-size/2,size,size);ctx.shadowBlur=0;ctx.lineWidth=3;ctx.strokeStyle=a;ctx.strokeRect(-size/2,-size/2,size,size);ctx.fillStyle=a;ctx.fillRect(-size*.18,-size*.1,size*.1,size*.1);ctx.fillRect(size*.08,-size*.1,size*.1,size*.1);ctx.strokeStyle=a;ctx.beginPath();ctx.moveTo(-size*.18,size*.17);ctx.lineTo(0,size*.24);ctx.lineTo(size*.18,size*.17);ctx.stroke();ctx.restore()}
function bg(ctx:CanvasRenderingContext2D,w:number,h:number,id:string,theme:string,camera:number){const b=item(id),t=THEMES[theme]||THEMES.neon;let c1=b.color||t[0],c2=b.accent||t[1];if(id==="bg-day"){c1="#63cbff";c2="#b8efff"}if(id==="bg-space"){c1="#070716";c2="#34205e"}if(id==="bg-lava"){c1="#21070a";c2="#76231b"}const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,c1);g.addColorStop(1,c2);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let i=0;i<20;i++){const x=((i*317-camera*.16)%(w+140))-70,y=60+(i*83%380);ctx.globalAlpha=.2;ctx.fillStyle=i%2?"#fff":t[2];ctx.beginPath();ctx.arc(x,y,12+i%4*7,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function sound(kind:string){try{const AC=window.AudioContext||((window as any).webkitAudioContext as typeof AudioContext);if(!AC)return;const a=new AC(),o=a.createOscillator(),g=a.createGain();const f=kind==="jump"?360:kind==="coin"?760:kind==="win"?560:130;o.type=kind==="death"?"sawtooth":"square";o.frequency.value=f;g.gain.value=.04;o.connect(g);g.connect(a.destination);o.start();o.frequency.exponentialRampToValueAtTime(f*(kind==="death"?.45:1.6),a.currentTime+.09);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.14);o.stop(a.currentTime+.15);setTimeout(()=>a.close(),220)}catch{}}

export default function GeometryDashGame(){
 const [view,setView]=useState<View>("home"),[save,setSave]=useState<Save>(DEFAULT),[ready,setReady]=useState(false),[levelId,setLevelId]=useState(1),[run,setRun]=useState<Run|null>(null),[paused,setPaused]=useState(false),[muted,setMuted]=useState(false),[tab,setTab]=useState<Tab>("skin"),[toast,setToast]=useState(""),[help,setHelp]=useState(false);
 const say=useCallback((s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)},[]);
 const missions=getMissions(save),daily=dailyInfo(save);
 const claimDaily=()=>{const info=dailyInfo(save);if(!info.ready){say("Ta récompense quotidienne est déjà récupérée. Reviens demain !");return}setSave(prev=>({...prev,coins:prev.coins+info.reward,dailyClaimDate:info.today,dailyStreak:info.streak}));say(`Récompense quotidienne : +${info.reward} pièces ! Série ${info.streak}/7 🔥`)};
 const claimMission=(id:string)=>{const mission=getMissions(save).find(m=>m.id===id);if(!mission||!mission.done||mission.claimed)return;setSave(prev=>({...prev,coins:prev.coins+mission.reward,claimedMissions:[...prev.claimedMissions,id]}));say(`Contrat terminé : +${mission.reward} pièces !`)};

 // Reading a saved client-side profile requires one hydration effect.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setSave({...DEFAULT,...JSON.parse(raw)})}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(save))},[ready,save]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if(view==="play"&&(e.code==="Space"||e.code==="ArrowUp"||e.code==="KeyW")){e.preventDefault();dispatchEvent(new CustomEvent("gd-jump"))}if(view==="play"&&e.code==="Escape")setPaused(x=>!x)};addEventListener("keydown",k);return()=>removeEventListener("keydown",k)},[view]);
 const start=(id:number,practice=false)=>{if(id>save.unlockedLevel)return;setLevelId(id);setRun({x:180,y:430,vy:0,rotation:0,onGround:true,deaths:0,coins:0,collected:[],shieldUsed:false,done:false,won:false,percent:0,practice,checkpointX:180,checkpointY:430,checkpointCoins:0,checkpointCollected:[]});setPaused(false);setView("play")};
 const buy=(it:ShopItem)=>{if((it.unlockLevel||1)>save.unlockedLevel){say(`Niveau ${it.unlockLevel} requis.`);return}if(save.owned.includes(it.id)){setSave(s=>({...s,...(it.category==="skin"?{skin:it.id}:it.category==="background"?{background:it.id}:{trail:it.id})}));say("Équipé ✨");return}if(save.coins<it.price){say("Pas assez de pièces.");return}setSave(s=>({...s,coins:s.coins-it.price,owned:[...s.owned,it.id],...(it.category==="skin"?{skin:it.id}:it.category==="background"?{background:it.id}:{trail:it.id})}));say(`${it.name} acheté 🔥`)};
 const upgrade=(id:UpgradeId)=>{const u=UPGRADES.find(x=>x.id===id),lv=save.upgrades[id]||0;if(!u||lv>=u.max)return;if(save.coins<u.costs[lv]){say("Pas assez de pièces.");return}setSave(s=>({...s,coins:s.coins-u.costs[lv],upgrades:{...s.upgrades,[id]:lv+1}}));say(`${u.name} niveau ${lv+1} ⚡`)};
 const finish=(l:GDLevel,r:Run)=>{const reward=Math.round((80+l.id*25+r.coins*(1+save.upgrades.multiplier*.1)+120)*(r.practice?0.35:1));setSave(s=>({...s,coins:s.coins+reward,unlockedLevel:Math.max(s.unlockedLevel,Math.min(LEVELS.length,l.id+1)),completed:s.completed.includes(l.id)?s.completed:[...s.completed,l.id],best:{...s.best,[l.id]:100},secretCoins:[...new Set([...s.secretCoins,...r.collected])]}));if(!muted)sound("win");setRun({...r,done:true,won:true,percent:100})};
 if(!ready)return <div className="gd-loading"><div className="gd-loader-cube"/><b>CHARGEMENT DU MONDE…</b></div>;
 const current=LEVELS.find(l=>l.id===levelId)||LEVELS[0],featured=LEVELS[Math.min(save.unlockedLevel-1,3)]||LEVELS[0];
 return <div className={view==="play"?"gd-app gd-playing":"gd-app"}>
  {view!=="play"&&<Nav view={view} go={setView} save={save} muted={muted} setMuted={setMuted}/>} 
  {view==="home"&&<HomeScreen save={save} featured={featured} start={start} go={setView} help={setHelp}/>}
  {view==="home"&&<MissionBoard save={save} missions={missions} dailyReady={daily.ready} dailyReward={daily.reward} dailyStreak={save.dailyStreak} claimDaily={claimDaily} claimMission={claimMission}/>}
  {view==="levels"&&<Levels save={save} selected={levelId} select={setLevelId} start={start} go={setView}/>} 
  {view==="shop"&&<Shop save={save} tab={tab} setTab={setTab} buy={buy} go={setView}/>} 
  {view==="upgrades"&&<Upgrades save={save} upgrade={upgrade} go={setView}/>} 
  {view==="play"&&run&&<Game level={current} save={save} run={run} paused={paused} muted={muted} setRun={setRun} setPaused={setPaused} finish={finish} retry={()=>start(current.id,run.practice)} exit={()=>{setRun(null);setView("levels")}}/>}
  {toast&&<div className="gd-toast">{toast}</div>}
  {help&&<div className="gd-modal-backdrop" onClick={()=>setHelp(false)}><div className="gd-help-modal" onClick={e=>e.stopPropagation()}><button className="gd-modal-x" onClick={()=>setHelp(false)}>×</button><span className="gd-kicker">COMMANDES</span><h2>Maîtrise ton cube.</h2><div className="gd-help-grid"><div><b>ESPACE / ↑ / W</b><span>Sauter</span></div><div><b>CLIC / TAP</b><span>Sauter</span></div><div><b>ÉCHAP</b><span>Pause</span></div><div><b>ORBES</b><span>Saute près de l&apos;orbe pour l&apos;activer</span></div></div><button className="gd-primary-btn" onClick={()=>{setHelp(false);start(featured.id)}}><Play size={17} fill="currentColor"/> C&apos;est parti</button></div></div>}
  {view!=="play"&&<footer className="gd-footer"><span>UNO → <b>GEOMETRY DASH WORLD</b></span><span>Progression locale sauvegardée automatiquement</span></footer>}
 </div>
}


function Nav({view,go,save,muted,setMuted}:{view:View;go:(v:View)=>void;save:Save;muted:boolean;setMuted:(v:boolean)=>void}){return <header className="gd-topbar"><button className="gd-logo" onClick={()=>go("home")}><span className="gd-logo-cube">✦</span><span><b>GEOMETRY</b><small>DASH // UNO WORLD</small></span></button><nav>{[["home","Accueil"],["levels","Niveaux"],["shop","Boutique"],["upgrades","Améliorations"]].map(([v,l])=><button key={v} className={view===v?"active":""} onClick={()=>go(v as View)}>{l}</button>)}</nav><div className="gd-nav-right"><span className="gd-coin-pill">◆ {save.coins}</span><button className="gd-icon-btn" onClick={()=>setMuted(!muted)}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}</button></div></header>}

function HomeScreen({save,featured,start,go,help}:{save:Save;featured:GDLevel;start:(n:number,practice?:boolean)=>void;go:(v:View)=>void;help:(b:boolean)=>void}){return <main className="gd-home"><section className="gd-hero"><div className="gd-hero-copy"><span className="gd-kicker"><Sparkles size={14}/> THE UNO WORLD HAS CHANGED</span><h1>RUN.<br/><span>JUMP.</span><br/>BREAK THE LIMIT.</h1><p>Un runner de précision façon Geometry Dash : 8 niveaux, 24 pièces secrètes, cubes, fonds, trails et améliorations permanentes.</p><div className="gd-hero-actions"><button className="gd-primary-btn big" onClick={()=>start(featured.id)}><Play size={19} fill="currentColor"/> JOUER</button><button className="gd-secondary-btn big" onClick={()=>go("levels")}><Gamepad2 size={19}/> NIVEAUX</button><button className="gd-secondary-btn big" onClick={()=>start(featured.id,true)}><RotateCcw size={17}/> PRACTICE</button></div><button className="gd-help-link" onClick={()=>help(true)}>Comment jouer ? →</button></div><HeroArt level={featured}/></section><div className="gd-stats-row"><Stat icon={<Trophy size={18}/>} v={`${save.completed.length}/${LEVELS.length}`} l="Niveaux terminés"/><Stat icon={<Coins size={18}/>} v={`${save.secretCoins.length}/24`} l="Pièces secrètes"/><Stat icon={<Zap size={18}/>} v={`LVL ${save.unlockedLevel}`} l="Progression"/><Stat icon={<Sparkles size={18}/>} v={`${save.owned.length}`} l="Objets"/></div><section className="gd-home-panels"><div className="gd-panel"><div className="gd-panel-head"><div><span className="gd-kicker">EN VEDETTE</span><h2>{featured.name}</h2></div><i className={`gd-diff ${cls(featured.difficulty)}`}>{diff(featured.difficulty)}</i></div><p>⚡ {Math.round(featured.speed)} vitesse · ◆ 3 pièces · record {save.best[featured.id]||0}%</p><button className="gd-secondary-btn" onClick={()=>start(featured.id)}>Continuer →</button></div><div className="gd-panel"><span className="gd-kicker">TON STYLE</span><h2>Personnalise ton run.</h2><div className="gd-mini-cards"><Mini it={item(save.skin)}/><Mini it={item(save.background)}/><Mini it={item(save.trail)}/></div><button className="gd-secondary-btn" onClick={()=>go("shop")}><ShoppingBag size={16}/> Boutique</button></div></section><section className="gd-callout"><div><span className="gd-kicker">NO CHECKPOINTS. NO EXCUSES.</span><h2>Chaque tentative te rapproche du 100%.</h2><p>Les bonnes runs commencent toujours par un premier essai.</p></div><button className="gd-primary-btn" onClick={()=>go("upgrades")}>DEVENIR PLUS FORT</button></section></main>}

function MissionBoard({save,missions,dailyReady,dailyReward,dailyStreak,claimDaily,claimMission}:{save:Save;missions:Mission[];dailyReady:boolean;dailyReward:number;dailyStreak:number;claimDaily:()=>void;claimMission:(id:string)=>void}){
 return <section className="gd-mission-board">
  <div className="gd-mission-head"><div><span className="gd-kicker">QUEST LOG // LIVE</span><h2>Les contrats du runner.</h2><p>Récupère tes bonus, complète les objectifs et remplis ton garage.</p></div><div className="gd-streak-chip"><Sparkles size={16}/><span><b>{dailyStreak}/7</b><small>jours de série</small></span></div></div>
  <div className="gd-quest-layout">
   <article className={`gd-daily-card ${dailyReady?"":"claimed"}`}><div className="gd-daily-orb"><Sparkles size={26}/></div><span className="gd-kicker">BONUS QUOTIDIEN</span><h3>{dailyReady?"Le coffre du jour":"À demain, champion."}</h3><p>{dailyReady?"Connecte-toi chaque jour pour augmenter ta récompense jusqu’à 7 jours de série.":"Tu as déjà ouvert ton coffre aujourd’hui. Ta série est conservée."}</p><div className="gd-daily-reward">◆ {dailyReady?dailyReward:"RÉCUPÉRÉ"}</div><button className="gd-primary-btn full" disabled={!dailyReady} onClick={claimDaily}>{dailyReady?"RÉCUPÉRER LE BONUS":"DÉJÀ RÉCUPÉRÉ"}</button></article>
   <div className="gd-quest-list">{missions.map(m=><article className={`gd-quest-card ${m.done?"complete":""} ${m.claimed?"claimed":""}`} key={m.id}><div className="gd-quest-check">{m.claimed?"✓":m.done?"★":"◆"}</div><div className="gd-quest-copy"><b>{m.title}</b><p>{m.description}</p><div className="gd-quest-progress"><span style={{width:`${Math.min(100,m.progress/m.target*100)}%`}}/></div><small>{m.progress}/{m.target} · récompense ◆ {m.reward}</small></div><button className="gd-quest-claim" disabled={!m.done||m.claimed} onClick={()=>claimMission(m.id)}>{m.claimed?"PRIS":m.done?"RÉCUPÉRER":"EN COURS"}</button></article>)}</div>
  </div>
 </section>
}

function Stat({icon,v,l}:{icon:ReactNode;v:string;l:string}){return <div className="gd-stat"><span>{icon}</span><div><b>{v}</b><small>{l}</small></div></div>}
function Mini({it}:{it:ShopItem}){return <div className="gd-mini-item"><div className="gd-mini-preview" style={{background:it.color||"#172042",boxShadow:`inset 0 0 30px ${(it.accent||"#72edff")}55`}}>{it.category==="skin"?"◆":it.category==="trail"?"✦":"☁"}</div><b>{it.name}</b></div>}
function HeroArt({level}:{level:GDLevel}){return <div className="gd-hero-art"><div className="gd-sun"/><div className="gd-grid-floor"/><div className="gd-art-platform p1"/><div className="gd-art-platform p2"/><div className="gd-art-spike s1"/><div className="gd-art-spike s2"/><div className="gd-art-spike s3"/><div className="gd-art-coin">◆</div><div className="gd-art-orb">●</div><div className="gd-art-cube"><span>• •</span><i>⌣</i></div><div className="gd-art-label"><b>LEVEL {level.id}</b><span>{level.name}</span><em>{diff(level.difficulty)}</em></div></div>}

function Levels({save,selected,select,start,go}:{save:Save;selected:number;select:(n:number)=>void;start:(n:number,practice?:boolean)=>void;go:(v:View)=>void}){const l=LEVELS.find(x=>x.id===selected)||LEVELS[0];return <main className="gd-screen"><div className="gd-screen-head"><div><span className="gd-kicker">WORLD MAP</span><h1>Choisis ton niveau.</h1><p>8 niveaux, 3 pièces secrètes chacun, difficulté qui monte jusqu&apos;au DEMON.</p></div><button className="gd-secondary-btn" onClick={()=>go("home")}><HomeIcon size={17}/> Accueil</button></div><div className="gd-level-layout"><div className="gd-level-list">{LEVELS.map(x=>{const lock=x.id>save.unlockedLevel;return <button key={x.id} disabled={lock} onClick={()=>select(x.id)} className={`gd-level-card ${selected===x.id?"selected":""} ${lock?"locked":""}`}><div className="gd-level-number">{lock?<Lock size={20}/>:String(x.id).padStart(2,"0")}</div><div className="gd-level-main"><b>{x.name}</b><span><i className={`gd-diff ${cls(x.difficulty)}`}>{diff(x.difficulty)}</i><em>{save.best[x.id]||0}%</em></span><div className="gd-level-bar"><span style={{width:`${save.best[x.id]||0}%`}}/></div></div><div className="gd-level-stars">{save.completed.includes(x.id)?"★":"☆"}</div></button>})}</div><div className="gd-level-detail"><span className="gd-kicker">LEVEL {l.id}</span><h2>{l.name}</h2><div className="gd-detail-tags"><i className={`gd-diff ${cls(l.difficulty)}`}>{diff(l.difficulty)}</i><span>⚡ {Math.round(l.speed)}</span><span>◆ 3</span></div><div className="gd-detail-visual"><div className="gd-detail-cube">• •<small>⌣</small></div><div className="gd-detail-spike"/><div className="gd-detail-spike two"/><div className="gd-detail-coin">◆</div></div><div className="gd-detail-row"><span>Record</span><b>{save.best[l.id]||0}%</b></div><div className="gd-detail-row"><span>Pièces</span><b>{l.coins.filter(c=>save.secretCoins.includes(c.id)).length}/3</b></div><button className="gd-primary-btn full" onClick={()=>start(l.id)}><Play size={18} fill="currentColor"/> LANCER</button><button className="gd-secondary-btn full gd-practice-button" onClick={()=>start(l.id,true)}><RotateCcw size={17}/> MODE PRACTICE · CHECKPOINTS AUTO</button></div></div></main>}

function Shop({save,tab,setTab,buy,go}:{save:Save;tab:Tab;setTab:(x:Tab)=>void;buy:(x:ShopItem)=>void;go:(v:View)=>void}){return <main className="gd-screen"><div className="gd-screen-head"><div><span className="gd-kicker">GARAGE</span><h1>Fabrique ton style.</h1><p>Cubes, fonds et trails : tout est visible en jeu.</p></div><span className="gd-head-coins">◆ {save.coins}</span></div><div className="gd-tabs">{([["skin","Cubes"],["background","Fonds"],["trail","Trails"]] as [Tab,string][]).map(([t,n])=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{n}</button>)}</div><div className="gd-shop-grid">{SHOP_ITEMS.filter(x=>x.category===tab).map(it=>{const own=save.owned.includes(it.id),eq=(it.category==="skin"?save.skin:it.category==="background"?save.background:save.trail)===it.id,lock=(it.unlockLevel||1)>save.unlockedLevel;return <div className={`gd-shop-card ${eq?"equipped":""}`} key={it.id}><div className="gd-shop-preview" style={{background:it.category==="background"?`radial-gradient(circle at 70% 30%,${it.accent},${it.color} 42%,#0b1027)`: `linear-gradient(135deg,${it.color},#11172f)`}}><div className="gd-preview-spark" style={{color:it.accent}}>{it.category==="skin"?"◆":it.category==="trail"?"✦ ✦ ✦":"☁ ✦ ☁"}</div></div><div className="gd-shop-copy"><b>{it.name}</b>{it.unlockLevel&&<span className="gd-lock-tag">LV {it.unlockLevel}</span>}<p>{it.description}</p><button className={own?"gd-secondary-btn":"gd-primary-btn"} disabled={lock||eq} onClick={()=>buy(it)}>{lock?<><Lock size={14}/> Verrouillé</>:eq?"ÉQUIPÉ":own?"ÉQUIPER":<>◆ {it.price}</>}</button></div></div>})}</div><button className="gd-back-bottom" onClick={()=>go("home")}>← Retour</button></main>}

function Upgrades({save,upgrade,go}:{save:Save;upgrade:(id:UpgradeId)=>void;go:(v:View)=>void}){return <main className="gd-screen"><div className="gd-screen-head"><div><span className="gd-kicker">POWER TREE</span><h1>Monte en puissance.</h1><p>Des bonus permanents pour les runs : saut, aimant, bouclier et pièces.</p></div><span className="gd-head-coins">◆ {save.coins}</span></div><div className="gd-upgrade-grid">{UPGRADES.map(u=>{const lv=save.upgrades[u.id]||0,c=u.costs[lv];return <div className="gd-upgrade-card" key={u.id}><div className="gd-upgrade-top"><div className="gd-upgrade-icon">{u.icon}</div><div><b>{u.name}</b><span>{lv}/{u.max}</span></div></div><p>{u.text}</p><div className="gd-upgrade-bars">{Array.from({length:u.max}).map((_,i)=><span key={i} className={i<lv?"on":""}/>)}</div><button className="gd-secondary-btn full" disabled={lv>=u.max} onClick={()=>upgrade(u.id)}>{lv>=u.max?"MAX":`Améliorer · ◆ ${c}`}</button></div>})}</div><div className="gd-upgrade-note"><Shield size={18}/><span><b>Conseil :</b> le bouclier absorbe une collision. L&apos;aimant aide à sécuriser les pièces sans ralentir le run.</span></div><button className="gd-back-bottom" onClick={()=>go("home")}>← Retour</button></main>}

function Game({level,save,run,paused,muted,setRun,setPaused,finish,retry,exit}:{level:GDLevel;save:Save;run:Run;paused:boolean;muted:boolean;setRun:(r:Run)=>void;setPaused:(v:boolean)=>void;finish:(l:GDLevel,r:Run)=>void;retry:()=>void;exit:()=>void}){
 const canvas=useRef<HTMLCanvasElement|null>(null),state=useRef(run),particles=useRef<Particle[]>([]),last=useRef(0),cam=useRef(0),[percent,setPercent]=useState(0),[flash,setFlash]=useState(0);
 const skin=item(save.skin),trail=item(save.trail);useEffect(()=>{state.current=run},[run]);
 const burst=useCallback((x:number,y:number,n=12)=>{for(let i=0;i<n;i++)particles.current.push({x,y,vx:(Math.random()-.5)*320,vy:(Math.random()-.7)*260,life:.6+Math.random()*.45,size:3+Math.random()*5,hue:Math.random()*360})},[]);
 const kill=useCallback(()=>{const s=state.current;if(s.done)return;if(s.practice){const n={...s,x:s.checkpointX,y:s.checkpointY,vy:0,rotation:0,onGround:true,deaths:s.deaths+1,coins:s.checkpointCoins,collected:[...s.checkpointCollected],shieldUsed:false,percent:Math.max(0,Math.round(s.checkpointX/level.length*100)),done:false,won:false};state.current=n;setRun(n);setFlash(1);burst(s.x+24,s.y+24,24);if(!muted)sound("death");return}if(save.upgrades.shield>0&&!s.shieldUsed){const n={...s,shieldUsed:true,vy:-740};state.current=n;setRun(n);burst(s.x+24,s.y+24,20);return}const n={...s,done:true,won:false,deaths:s.deaths+1};state.current=n;setRun(n);setFlash(1);burst(s.x+24,s.y+24,30);if(!muted)sound("death")},[burst,level,muted,save.upgrades.shield,setRun]);
 const jump=useCallback(()=>{if(paused||state.current.done)return;const s=state.current,power=900*(1+save.upgrades.jump*.07);let n:Run|null=null;if(s.onGround)n={...s,vy:-power,onGround:false};else{const o=level.orbs.find(x=>Math.abs(x.x-(s.x+24))<78&&Math.abs(x.y-(s.y+24))<90);if(o)n={...s,vy:-o.power,onGround:false}}if(n){state.current=n;setRun(n);burst(s.x+24,s.y+44,7);if(!muted)sound("jump")}},[burst,level,muted,paused,save.upgrades.jump,setRun]);
 useEffect(()=>{const h=()=>jump();addEventListener("gd-jump",h);const c=canvas.current;if(!c)return()=>removeEventListener("gd-jump",h);const p=(e:PointerEvent)=>{if(e.button===0)jump()};c.addEventListener("pointerdown",p);return()=>{removeEventListener("gd-jump",h);c.removeEventListener("pointerdown",p)}},[jump]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;const resize=()=>{const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)};resize();addEventListener("resize",resize);let raf=0;const draw=(t:number)=>{raf=requestAnimationFrame(draw);const w=c.clientWidth||1200,h=c.clientHeight||650,dt=Math.min((t-last.current||16)/1000,.034);last.current=t;let s=state.current;
  if(!paused&&!s.done){let x=s.x+level.speed*dt,vy=s.vy+2450*dt,y=s.y+vy*dt,grounded=false;for(const p of level.platforms){if(x+41>p.x&&x+7<p.x+p.w&&vy>=0&&s.y+48<=p.y+8&&y+48>=p.y){y=p.y-48;vy=0;grounded=true}}
   const pad=level.pads.find(p=>Math.abs(p.x-x)<34&&Math.abs(y+48-p.y)<20);if(pad&&grounded){vy=-pad.power;grounded=false;burst(x+24,y+46,13)}
   const spike=level.spikes.some(a=>x+44>a.x&&x+7<a.x+(a.count||1)*34&&y+45>a.y-42&&y+8<a.y+4);const collision=spike||y>h+150;if(collision){kill();s=state.current;x=s.x;y=s.y;vy=s.vy;grounded=s.onGround}if(s.done){s=state.current}else{
   const collected=[...state.current.collected];let gained=s.coins,rad=58+save.upgrades.magnet*36;for(const coin of level.coins){if(collected.includes(coin.id))continue;const d=Math.hypot(coin.x-(x+24),coin.y-(y+24));if(d<rad&&(d<38||save.upgrades.magnet>=2)){collected.push(coin.id);gained++;burst(coin.x,coin.y,10);if(!muted)sound("coin")}}
   const pc=Math.max(0,Math.min(100,Math.round(x/level.length*100)));if(pc!==s.percent)setPercent(pc);const checkpointDue=s.practice&&grounded&&x>=s.checkpointX+1800;const checkpointX=checkpointDue?x:s.checkpointX;const checkpointY=checkpointDue?y:s.checkpointY;const checkpointCoins=checkpointDue?gained:s.checkpointCoins;const checkpointCollected=checkpointDue?[...collected]:s.checkpointCollected;const n={...s,x,y,vy,rotation:s.rotation+(grounded?0:8*dt),onGround:grounded,coins:gained,collected,percent:pc,checkpointX,checkpointY,checkpointCoins,checkpointCollected};if(checkpointDue)burst(x+24,y+24,16);state.current=n;setRun(n);if(x>=level.length&&!n.done){const done={...n,done:true,won:true,percent:100};state.current=done;setRun(done);finish(level,done)}}}
  cam.current=Math.max(0,state.current.x-w*.24);bg(ctx,w,h,save.background,level.theme,cam.current);ctx.save();ctx.translate(-cam.current,0);const th=THEMES[level.theme];for(const p of level.platforms){if(p.x+p.w<cam.current-80||p.x>cam.current+w+80)continue;ctx.fillStyle=th[1];ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle=th[2];ctx.fillRect(p.x,p.y,p.w,5)}for(const sp of level.spikes){ctx.fillStyle="#f5f7ff";ctx.shadowBlur=12;ctx.shadowColor=th[2];for(let i=0;i<(sp.count||1);i++){const sx=sp.x+i*34;ctx.beginPath();ctx.moveTo(sx,sp.y);ctx.lineTo(sx+17,sp.y-42);ctx.lineTo(sx+34,sp.y);ctx.closePath();ctx.fill()}ctx.shadowBlur=0}for(const p of level.pads){ctx.fillStyle=p.color==="yellow"?"#ffd43b":"#ff5ab7";rounded(ctx,p.x,p.y-7,54,12,5);ctx.fill()}for(const o of level.orbs){ctx.beginPath();ctx.arc(o.x,o.y,17,0,Math.PI*2);ctx.fillStyle=o.color==="yellow"?"#ffd43b":o.color==="pink"?"#ff61ca":"#5ab3ff";ctx.shadowBlur=22;ctx.shadowColor=ctx.fillStyle;ctx.fillStyle;ctx.fill();ctx.shadowBlur=0}for(const coin of level.coins){if(state.current.collected.includes(coin.id))continue;ctx.save();ctx.translate(coin.x,coin.y);ctx.rotate(t/500+coin.x);ctx.fillStyle="#ffdc4b";ctx.shadowBlur=16;ctx.shadowColor="#ffe06a";ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(14,0);ctx.lineTo(0,18);ctx.lineTo(-14,0);ctx.closePath();ctx.fill();ctx.restore()}for(let i=particles.current.length-1;i>=0;i--){const p=particles.current[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt;p.life-=dt;if(p.life<=0)particles.current.splice(i,1);else{ctx.globalAlpha=p.life;ctx.fillStyle=trail.id==="trail-rainbow"?`hsl(${(p.hue+t/6)%360},100%,65%)`:(trail.color||th[2]);ctx.fillRect(p.x,p.y,p.size,p.size)}}ctx.globalAlpha=1;if(trail.id!=="trail-none"&&!state.current.done){for(let q=0;q<4;q++){ctx.globalAlpha=.35-q*.07;ctx.fillStyle=trail.id==="trail-rainbow"?`hsl(${(t/6+q*50)%360},100%,65%)`:(trail.color||th[2]);ctx.fillRect(state.current.x+6-q*15,state.current.y+20,8-q,8-q)}}ctx.globalAlpha=1;cube(ctx,state.current.x,state.current.y,48,skin,state.current.rotation);ctx.restore();if(flash>0){ctx.fillStyle=`rgba(255,54,89,${Math.min(.4,flash*.4)})`;ctx.fillRect(0,0,w,h);setFlash(x=>Math.max(0,x-.08))}};raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize)}},[finish,flash,kill,level,muted,paused,save,skin,setRun,trail,burst]);
 return <div className="gd-game-shell"><canvas ref={canvas} className="gd-canvas"/><div className="gd-hud-top"><button className="gd-hud-btn" onClick={exit}><HomeIcon size={17}/></button><div className="gd-hud-title"><b>{level.name}</b><span>{diff(level.difficulty)}</span></div><div className="gd-hud-right"><span>◆ {run.coins}</span><span>☠ {run.deaths}</span><button className="gd-hud-btn" onClick={()=>setPaused(!paused)}>{paused?<Play size={17}/>:<Pause size={17}/>}</button></div></div><div className="gd-progress"><span style={{width:`${percent}%`}}/><b>{percent}%</b></div><div className="gd-run-bottom"><span>◆ {run.collected.length}/3</span><span>{run.practice?"MODE PRACTICE · CHECKPOINTS AUTO":save.upgrades.shield?(run.shieldUsed?"◇ BOUCLIER UTILISÉ":"◇ BOUCLIER PRÊT"):"ESPACE / CLIC = SAUT"}</span></div><button className="gd-mobile-jump" onPointerDown={e=>{e.preventDefault();jump()}}>JUMP</button>
 {paused&&!run.done&&<div className="gd-pause-overlay"><div className="gd-pause-card"><span className="gd-kicker">PAUSE</span><h2>Tu respires.</h2><div className="gd-pause-stats"><span><b>{percent}%</b><small>progression</small></span><span><b>{run.coins}</b><small>pièces</small></span><span><b>{run.deaths}</b><small>morts</small></span></div><button className="gd-primary-btn full" onClick={()=>setPaused(false)}><Play size={17}/> REPRENDRE</button><button className="gd-secondary-btn full" onClick={retry}><RotateCcw size={17}/> RECOMMENCER</button><button className="gd-text-btn" onClick={exit}>Quitter</button></div></div>}
 {run.done&&<div className="gd-pause-overlay"><div className={`gd-result-card ${run.won?"win":"fail"}`}><div className="gd-result-icon">{run.won?<Crown size={33}/>:<RotateCcw size={33}/>}</div><span className="gd-kicker">{run.won?"LEVEL COMPLETE":"RETRY"}</span><h2>{run.won?level.name:"Encore un effort."}</h2><p>{run.won?`Tu as fini avec ${run.collected.length}/3 pièces.`:`Tu as atteint ${percent}%.`}</p>{run.won&&<div className="gd-reward-box"><span>RÉCOMPENSE</span><b>+{Math.round((80+level.id*25+run.coins*(1+save.upgrades.multiplier*.1)+120)*(run.practice?0.35:1))} ◆</b></div>}<button className="gd-primary-btn full" onClick={retry}>{run.won?"REJOUER":"RÉESSAYER"}</button>{run.won&&<button className="gd-secondary-btn full" onClick={exit}>AUTRE NIVEAU</button>}{!run.won&&<button className="gd-secondary-btn full" onClick={exit}>QUITTER</button>}</div></div>}
 </div>}
